# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArmUi.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1200, 620)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        Form.setMaximumSize(QtCore.QSize(1200, 620))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        Form.setFont(font)
        Form.setFocusPolicy(QtCore.Qt.NoFocus)
        Form.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 1200, 600))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.widget_id6 = QtWidgets.QWidget(self.tab_1)
        self.widget_id6.setGeometry(QtCore.QRect(240, 420, 120, 110))
        self.widget_id6.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id6.setObjectName("widget_id6")
        self.label_ID6 = QtWidgets.QLabel(self.widget_id6)
        self.label_ID6.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID6.setFont(font)
        self.label_ID6.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID6.setObjectName("label_ID6")
        self.horizontalSlider_6 = QtWidgets.QSlider(self.widget_id6)
        self.horizontalSlider_6.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_6.setAutoFillBackground(False)
        self.horizontalSlider_6.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_6.setMinimum(0)
        self.horizontalSlider_6.setMaximum(1000)
        self.horizontalSlider_6.setPageStep(1)
        self.horizontalSlider_6.setProperty("value", 500)
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_id6)
        self.lineEdit_6.setGeometry(QtCore.QRect(44, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setAutoFillBackground(False)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_6.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_6.setReadOnly(False)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_16 = QtWidgets.QLabel(self.widget_id6)
        self.label_16.setGeometry(QtCore.QRect(90, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_16.setObjectName("label_16")
        self.label_d6 = QtWidgets.QLabel(self.widget_id6)
        self.label_d6.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d6.setFont(font)
        self.label_d6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d6.setObjectName("label_d6")
        self.label_18 = QtWidgets.QLabel(self.widget_id6)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_18.setObjectName("label_18")
        self.horizontalSlider_16 = QtWidgets.QSlider(self.widget_id6)
        self.horizontalSlider_16.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_16.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_16.setMinimum(-125)
        self.horizontalSlider_16.setMaximum(125)
        self.horizontalSlider_16.setPageStep(1)
        self.horizontalSlider_16.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_16.setObjectName("horizontalSlider_16")
        self.widget_5 = QtWidgets.QWidget(self.tab_1)
        self.widget_5.setGeometry(QtCore.QRect(910, 360, 281, 211))
        self.widget_5.setStyleSheet("#widget_5 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_5.setObjectName("widget_5")
        self.label_action = QtWidgets.QLabel(self.widget_5)
        self.label_action.setGeometry(QtCore.QRect(5, 20, 111, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_action.setFont(font)
        self.label_action.setObjectName("label_action")
        self.comboBox_action = QtWidgets.QComboBox(self.widget_5)
        self.comboBox_action.setGeometry(QtCore.QRect(120, 20, 71, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox_action.setFont(font)
        self.comboBox_action.setStyleSheet("background-color: rgb(240, 240, 240);\n"
"")
        self.comboBox_action.setObjectName("comboBox_action")
        self.Button_DelectSingle = QtWidgets.QPushButton(self.widget_5)
        self.Button_DelectSingle.setGeometry(QtCore.QRect(10, 60, 140, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectSingle.setFont(font)
        self.Button_DelectSingle.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectSingle.setObjectName("Button_DelectSingle")
        self.Button_AllDelect = QtWidgets.QPushButton(self.widget_5)
        self.Button_AllDelect.setGeometry(QtCore.QRect(160, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AllDelect.setFont(font)
        self.Button_AllDelect.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AllDelect.setObjectName("Button_AllDelect")
        self.Button_RunAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_RunAction.setGeometry(QtCore.QRect(10, 110, 140, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_RunAction.setFont(font)
        self.Button_RunAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_RunAction.setObjectName("Button_RunAction")
        self.Button_StopAction = QtWidgets.QPushButton(self.widget_5)
        self.Button_StopAction.setGeometry(QtCore.QRect(160, 110, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_StopAction.setFont(font)
        self.Button_StopAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_StopAction.setObjectName("Button_StopAction")
        self.Button_Quit = QtWidgets.QPushButton(self.widget_5)
        self.Button_Quit.setGeometry(QtCore.QRect(100, 160, 100, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_Quit.setFont(font)
        self.Button_Quit.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Quit.setObjectName("Button_Quit")
        self.Button_Reflash = QtWidgets.QPushButton(self.widget_5)
        self.Button_Reflash.setGeometry(QtCore.QRect(200, 12, 71, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_Reflash.setFont(font)
        self.Button_Reflash.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Reflash.setObjectName("Button_Reflash")
        self.widget_3 = QtWidgets.QWidget(self.tab_1)
        self.widget_3.setGeometry(QtCore.QRect(670, 360, 90, 211))
        self.widget_3.setStyleSheet("#widget_3 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_3.setObjectName("widget_3")
        self.checkBox = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox.setGeometry(QtCore.QRect(20, 40, 61, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.Button_Run = QtWidgets.QPushButton(self.widget_3)
        self.Button_Run.setGeometry(QtCore.QRect(10, 100, 70, 81))
        font = QtGui.QFont()
        font.setFamily("SimHei")
        font.setPointSize(20)
        self.Button_Run.setFont(font)
        self.Button_Run.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_Run.setIconSize(QtCore.QSize(14, 14))
        self.Button_Run.setObjectName("Button_Run")
        self.widget_2 = QtWidgets.QWidget(self.tab_1)
        self.widget_2.setGeometry(QtCore.QRect(485, 360, 181, 211))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.widget_2.setFont(font)
        self.widget_2.setStyleSheet("#widget_2 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_2.setObjectName("widget_2")
        self.Button_ReadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReadDeviation.setGeometry(QtCore.QRect(10, 15, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReadDeviation.setFont(font)
        self.Button_ReadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReadDeviation.setObjectName("Button_ReadDeviation")
        self.Button_DownloadDeviation = QtWidgets.QPushButton(self.widget_2)
        self.Button_DownloadDeviation.setGeometry(QtCore.QRect(10, 80, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DownloadDeviation.setFont(font)
        self.Button_DownloadDeviation.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DownloadDeviation.setObjectName("Button_DownloadDeviation")
        self.Button_ReSetServos = QtWidgets.QPushButton(self.widget_2)
        self.Button_ReSetServos.setGeometry(QtCore.QRect(10, 140, 160, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ReSetServos.setFont(font)
        self.Button_ReSetServos.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ReSetServos.setObjectName("Button_ReSetServos")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_1)
        self.tableWidget.setGeometry(QtCore.QRect(485, 0, 711, 231))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);")
        self.tableWidget.setTextElideMode(QtCore.Qt.ElideMiddle)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignTop)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(79)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(20)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(22)
        self.tableWidget.verticalHeader().setMinimumSectionSize(22)
        self.widget_4 = QtWidgets.QWidget(self.tab_1)
        self.widget_4.setGeometry(QtCore.QRect(765, 360, 141, 211))
        self.widget_4.setStyleSheet("#widget_4 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_4.setObjectName("widget_4")
        self.Button_OpenActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_OpenActionGroup.setGeometry(QtCore.QRect(5, 15, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_OpenActionGroup.setFont(font)
        self.Button_OpenActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_OpenActionGroup.setObjectName("Button_OpenActionGroup")
        self.Button_SaveActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_SaveActionGroup.setGeometry(QtCore.QRect(5, 80, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_SaveActionGroup.setFont(font)
        self.Button_SaveActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_SaveActionGroup.setObjectName("Button_SaveActionGroup")
        self.Button_TandemActionGroup = QtWidgets.QPushButton(self.widget_4)
        self.Button_TandemActionGroup.setGeometry(QtCore.QRect(5, 145, 130, 51))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_TandemActionGroup.setFont(font)
        self.Button_TandemActionGroup.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_TandemActionGroup.setObjectName("Button_TandemActionGroup")
        self.widget_1 = QtWidgets.QWidget(self.tab_1)
        self.widget_1.setGeometry(QtCore.QRect(485, 240, 711, 111))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.widget_1.setFont(font)
        self.widget_1.setStyleSheet("#widget_1 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_1.setObjectName("widget_1")
        self.label_time = QtWidgets.QLabel(self.widget_1)
        self.label_time.setGeometry(QtCore.QRect(20, 20, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.lineEdit_time = QtWidgets.QLineEdit(self.widget_1)
        self.lineEdit_time.setGeometry(QtCore.QRect(140, 20, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.lineEdit_time.setFont(font)
        self.lineEdit_time.setMaxLength(30000)
        self.lineEdit_time.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_time.setObjectName("lineEdit_time")
        self.Button_AddAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_AddAction.setGeometry(QtCore.QRect(350, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AddAction.setFont(font)
        self.Button_AddAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AddAction.setObjectName("Button_AddAction")
        self.Button_DelectAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAction.setGeometry(QtCore.QRect(350, 60, 110, 17))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectAction.setFont(font)
        self.Button_DelectAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAction.setObjectName("Button_DelectAction")
        self.Button_UpdateAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_UpdateAction.setGeometry(QtCore.QRect(470, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_UpdateAction.setFont(font)
        self.Button_UpdateAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_UpdateAction.setObjectName("Button_UpdateAction")
        self.Button_InsertAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_InsertAction.setGeometry(QtCore.QRect(470, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_InsertAction.setFont(font)
        self.Button_InsertAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_InsertAction.setObjectName("Button_InsertAction")
        self.Button_ServoPowerDown = QtWidgets.QPushButton(self.widget_1)
        self.Button_ServoPowerDown.setGeometry(QtCore.QRect(220, 10, 120, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_ServoPowerDown.setFont(font)
        self.Button_ServoPowerDown.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_ServoPowerDown.setObjectName("Button_ServoPowerDown")
        self.Button_AngularReadback = QtWidgets.QPushButton(self.widget_1)
        self.Button_AngularReadback.setGeometry(QtCore.QRect(220, 60, 120, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_AngularReadback.setFont(font)
        self.Button_AngularReadback.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_AngularReadback.setObjectName("Button_AngularReadback")
        self.Button_MoveUpAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveUpAction.setGeometry(QtCore.QRect(590, 10, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_MoveUpAction.setFont(font)
        self.Button_MoveUpAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveUpAction.setObjectName("Button_MoveUpAction")
        self.Button_MoveDownAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_MoveDownAction.setGeometry(QtCore.QRect(590, 60, 110, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_MoveDownAction.setFont(font)
        self.Button_MoveDownAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_MoveDownAction.setObjectName("Button_MoveDownAction")
        self.label_time_2 = QtWidgets.QLabel(self.widget_1)
        self.label_time_2.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_time_2.setFont(font)
        self.label_time_2.setObjectName("label_time_2")
        self.label = QtWidgets.QLabel(self.widget_1)
        self.label.setGeometry(QtCore.QRect(190, 25, 16, 21))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.widget_1)
        self.label_5.setGeometry(QtCore.QRect(190, 65, 16, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_TotalTime = QtWidgets.QLabel(self.widget_1)
        self.label_TotalTime.setGeometry(QtCore.QRect(130, 65, 60, 20))
        self.label_TotalTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_TotalTime.setAlignment(QtCore.Qt.AlignCenter)
        self.label_TotalTime.setObjectName("label_TotalTime")
        self.Button_DelectAllAction = QtWidgets.QPushButton(self.widget_1)
        self.Button_DelectAllAction.setGeometry(QtCore.QRect(350, 83, 110, 17))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Button_DelectAllAction.setFont(font)
        self.Button_DelectAllAction.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.Button_DelectAllAction.setObjectName("Button_DelectAllAction")
        self.widget_id5 = QtWidgets.QWidget(self.tab_1)
        self.widget_id5.setGeometry(QtCore.QRect(280, 305, 120, 110))
        self.widget_id5.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id5.setObjectName("widget_id5")
        self.horizontalSlider_5 = QtWidgets.QSlider(self.widget_id5)
        self.horizontalSlider_5.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_5.setAutoFillBackground(False)
        self.horizontalSlider_5.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_5.setMinimum(0)
        self.horizontalSlider_5.setMaximum(1000)
        self.horizontalSlider_5.setPageStep(1)
        self.horizontalSlider_5.setProperty("value", 500)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.label_ID5 = QtWidgets.QLabel(self.widget_id5)
        self.label_ID5.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID5.setFont(font)
        self.label_ID5.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID5.setObjectName("label_ID5")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_id5)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setAutoFillBackground(False)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_5.setReadOnly(False)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_13 = QtWidgets.QLabel(self.widget_id5)
        self.label_13.setGeometry(QtCore.QRect(90, 50, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_13.setObjectName("label_13")
        self.label_d5 = QtWidgets.QLabel(self.widget_id5)
        self.label_d5.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d5.setFont(font)
        self.label_d5.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d5.setObjectName("label_d5")
        self.label_15 = QtWidgets.QLabel(self.widget_id5)
        self.label_15.setGeometry(QtCore.QRect(0, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_15.setObjectName("label_15")
        self.horizontalSlider_15 = QtWidgets.QSlider(self.widget_id5)
        self.horizontalSlider_15.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_15.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_15.setMinimum(-125)
        self.horizontalSlider_15.setMaximum(125)
        self.horizontalSlider_15.setPageStep(1)
        self.horizontalSlider_15.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_15.setObjectName("horizontalSlider_15")
        self.widget_id1 = QtWidgets.QWidget(self.tab_1)
        self.widget_id1.setGeometry(QtCore.QRect(40, 55, 120, 110))
        self.widget_id1.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id1.setObjectName("widget_id1")
        self.label_ID1 = QtWidgets.QLabel(self.widget_id1)
        self.label_ID1.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID1.setFont(font)
        self.label_ID1.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID1.setObjectName("label_ID1")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_1.setAutoFillBackground(False)
        self.horizontalSlider_1.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_1.setMinimum(0)
        self.horizontalSlider_1.setMaximum(1000)
        self.horizontalSlider_1.setPageStep(1)
        self.horizontalSlider_1.setProperty("value", 500)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.widget_id1)
        self.lineEdit_1.setGeometry(QtCore.QRect(47, 50, 38, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_1.setFont(font)
        self.lineEdit_1.setAutoFillBackground(False)
        self.lineEdit_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_1.setMaxLength(1000)
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setDragEnabled(False)
        self.lineEdit_1.setReadOnly(False)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalSlider_11 = QtWidgets.QSlider(self.widget_id1)
        self.horizontalSlider_11.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_11.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_11.setMinimum(-125)
        self.horizontalSlider_11.setMaximum(125)
        self.horizontalSlider_11.setPageStep(1)
        self.horizontalSlider_11.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_11.setObjectName("horizontalSlider_11")
        self.label_d1 = QtWidgets.QLabel(self.widget_id1)
        self.label_d1.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d1.setFont(font)
        self.label_d1.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d1.setObjectName("label_d1")
        self.label_2 = QtWidgets.QLabel(self.widget_id1)
        self.label_2.setGeometry(QtCore.QRect(0, 55, 48, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget_id1)
        self.label_3.setGeometry(QtCore.QRect(85, 55, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_3.setObjectName("label_3")
        self.widget_id4 = QtWidgets.QWidget(self.tab_1)
        self.widget_id4.setGeometry(QtCore.QRect(350, 190, 120, 110))
        self.widget_id4.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id4.setObjectName("widget_id4")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.widget_id4)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_4.setAutoFillBackground(False)
        self.horizontalSlider_4.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_4.setMinimum(0)
        self.horizontalSlider_4.setMaximum(1000)
        self.horizontalSlider_4.setPageStep(1)
        self.horizontalSlider_4.setProperty("value", 500)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_ID4 = QtWidgets.QLabel(self.widget_id4)
        self.label_ID4.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID4.setFont(font)
        self.label_ID4.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID4.setObjectName("label_ID4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_id4)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setAutoFillBackground(False)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setReadOnly(False)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_10 = QtWidgets.QLabel(self.widget_id4)
        self.label_10.setGeometry(QtCore.QRect(85, 50, 41, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_10.setObjectName("label_10")
        self.label_d4 = QtWidgets.QLabel(self.widget_id4)
        self.label_d4.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d4.setFont(font)
        self.label_d4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d4.setObjectName("label_d4")
        self.label_12 = QtWidgets.QLabel(self.widget_id4)
        self.label_12.setGeometry(QtCore.QRect(10, 50, 21, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_12.setObjectName("label_12")
        self.horizontalSlider_14 = QtWidgets.QSlider(self.widget_id4)
        self.horizontalSlider_14.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_14.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_14.setMinimum(-125)
        self.horizontalSlider_14.setMaximum(125)
        self.horizontalSlider_14.setPageStep(1)
        self.horizontalSlider_14.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_14.setObjectName("horizontalSlider_14")
        self.widget_id2 = QtWidgets.QWidget(self.tab_1)
        self.widget_id2.setGeometry(QtCore.QRect(180, 60, 120, 110))
        self.widget_id2.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id2.setObjectName("widget_id2")
        self.label_ID2 = QtWidgets.QLabel(self.widget_id2)
        self.label_ID2.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID2.setFont(font)
        self.label_ID2.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID2.setObjectName("label_ID2")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.widget_id2)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_2.setAutoFillBackground(False)
        self.horizontalSlider_2.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_2.setMinimum(0)
        self.horizontalSlider_2.setMaximum(1000)
        self.horizontalSlider_2.setPageStep(1)
        self.horizontalSlider_2.setProperty("value", 500)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_id2)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setReadOnly(False)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.widget_id2)
        self.label_4.setGeometry(QtCore.QRect(10, 55, 21, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_4.setObjectName("label_4")
        self.label_d2 = QtWidgets.QLabel(self.widget_id2)
        self.label_d2.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d2.setFont(font)
        self.label_d2.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d2.setTextFormat(QtCore.Qt.AutoText)
        self.label_d2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d2.setObjectName("label_d2")
        self.label_6 = QtWidgets.QLabel(self.widget_id2)
        self.label_6.setGeometry(QtCore.QRect(85, 55, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_6.setObjectName("label_6")
        self.horizontalSlider_12 = QtWidgets.QSlider(self.widget_id2)
        self.horizontalSlider_12.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_12.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_12.setMinimum(-125)
        self.horizontalSlider_12.setMaximum(125)
        self.horizontalSlider_12.setPageStep(1)
        self.horizontalSlider_12.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_12.setObjectName("horizontalSlider_12")
        self.widget_id3 = QtWidgets.QWidget(self.tab_1)
        self.widget_id3.setGeometry(QtCore.QRect(320, 70, 120, 110))
        self.widget_id3.setStyleSheet("background-color: rgb(255, 165, 0, 200);\n"
"border-radius:10px;")
        self.widget_id3.setObjectName("widget_id3")
        self.label_ID3 = QtWidgets.QLabel(self.widget_id3)
        self.label_ID3.setGeometry(QtCore.QRect(50, 0, 32, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_ID3.setFont(font)
        self.label_ID3.setStyleSheet("background-color: rgb(255, 255, 255， 0);\n"
"border-radius:0px;")
        self.label_ID3.setObjectName("label_ID3")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.widget_id3)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 20, 100, 22))
        self.horizontalSlider_3.setAutoFillBackground(False)
        self.horizontalSlider_3.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius:0px;")
        self.horizontalSlider_3.setMinimum(0)
        self.horizontalSlider_3.setMaximum(1000)
        self.horizontalSlider_3.setPageStep(1)
        self.horizontalSlider_3.setProperty("value", 500)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_id3)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 50, 41, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:0px;")
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setReadOnly(False)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_7 = QtWidgets.QLabel(self.widget_id3)
        self.label_7.setGeometry(QtCore.QRect(90, 55, 31, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_7.setObjectName("label_7")
        self.label_d3 = QtWidgets.QLabel(self.widget_id3)
        self.label_d3.setGeometry(QtCore.QRect(5, 87, 31, 16))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(10)
        self.label_d3.setFont(font)
        self.label_d3.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_d3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_d3.setObjectName("label_d3")
        self.label_9 = QtWidgets.QLabel(self.widget_id3)
        self.label_9.setGeometry(QtCore.QRect(0, 55, 36, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.label_9.setObjectName("label_9")
        self.horizontalSlider_13 = QtWidgets.QSlider(self.widget_id3)
        self.horizontalSlider_13.setGeometry(QtCore.QRect(35, 85, 50, 20))
        self.horizontalSlider_13.setStyleSheet("background-color: rgb(255, 255, 255， 0);")
        self.horizontalSlider_13.setMinimum(-125)
        self.horizontalSlider_13.setMaximum(125)
        self.horizontalSlider_13.setPageStep(1)
        self.horizontalSlider_13.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_13.setObjectName("horizontalSlider_13")
        self.frame = QtWidgets.QFrame(self.tab_1)
        self.frame.setGeometry(QtCore.QRect(-15, 5, 498, 511))
        self.frame.setStyleSheet("background-image: url(:/images/xArmUi.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton_zn = QtWidgets.QRadioButton(self.frame)
        self.radioButton_zn.setGeometry(QtCore.QRect(20, 10, 61, 27))
        self.radioButton_zn.setObjectName("radioButton_zn")
        self.radioButton_en = QtWidgets.QRadioButton(self.frame)
        self.radioButton_en.setGeometry(QtCore.QRect(100, 10, 81, 27))
        self.radioButton_en.setObjectName("radioButton_en")
        self.frame.raise_()
        self.widget_id6.raise_()
        self.widget_5.raise_()
        self.widget_3.raise_()
        self.widget_2.raise_()
        self.tableWidget.raise_()
        self.widget_4.raise_()
        self.widget_1.raise_()
        self.widget_id5.raise_()
        self.widget_id1.raise_()
        self.widget_id4.raise_()
        self.widget_id2.raise_()
        self.widget_id3.raise_()
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.pushButton_read = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_read.setGeometry(QtCore.QRect(230, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_read.setFont(font)
        self.pushButton_read.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_read.setObjectName("pushButton_read")
        self.pushButton_set = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_set.setGeometry(QtCore.QRect(430, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_set.setFont(font)
        self.pushButton_set.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_set.setObjectName("pushButton_set")
        self.pushButton_default = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_default.setGeometry(QtCore.QRect(630, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_default.setFont(font)
        self.pushButton_default.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_default.setObjectName("pushButton_default")
        self.widget = QtWidgets.QWidget(self.tab_2)
        self.widget.setGeometry(QtCore.QRect(460, 90, 220, 160))
        self.widget.setStyleSheet("#widget {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget.setObjectName("widget")
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setGeometry(QtCore.QRect(63, 10, 101, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.horizontalSlider_servoMin = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_servoMin.setGeometry(QtCore.QRect(30, 60, 160, 22))
        self.horizontalSlider_servoMin.setMaximum(1000)
        self.horizontalSlider_servoMin.setPageStep(1)
        self.horizontalSlider_servoMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMin.setObjectName("horizontalSlider_servoMin")
        self.horizontalSlider_servoMax = QtWidgets.QSlider(self.widget)
        self.horizontalSlider_servoMax.setGeometry(QtCore.QRect(30, 120, 160, 22))
        self.horizontalSlider_servoMax.setMinimum(0)
        self.horizontalSlider_servoMax.setMaximum(1000)
        self.horizontalSlider_servoMax.setPageStep(1)
        self.horizontalSlider_servoMax.setProperty("value", 1000)
        self.horizontalSlider_servoMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMax.setObjectName("horizontalSlider_servoMax")
        self.label_servoMin = QtWidgets.QLabel(self.widget)
        self.label_servoMin.setGeometry(QtCore.QRect(15, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMin.setFont(font)
        self.label_servoMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMin.setObjectName("label_servoMin")
        self.label_servoMax = QtWidgets.QLabel(self.widget)
        self.label_servoMax.setGeometry(QtCore.QRect(160, 90, 41, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMax.setFont(font)
        self.label_servoMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMax.setObjectName("label_servoMax")
        self.widget_6 = QtWidgets.QWidget(self.tab_2)
        self.widget_6.setGeometry(QtCore.QRect(460, 280, 220, 160))
        self.widget_6.setStyleSheet("#widget_6 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_6.setObjectName("widget_6")
        self.label_19 = QtWidgets.QLabel(self.widget_6)
        self.label_19.setGeometry(QtCore.QRect(63, 10, 111, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.horizontalSlider_servoMinV = QtWidgets.QSlider(self.widget_6)
        self.horizontalSlider_servoMinV.setGeometry(QtCore.QRect(30, 60, 160, 22))
        self.horizontalSlider_servoMinV.setMinimum(45)
        self.horizontalSlider_servoMinV.setMaximum(140)
        self.horizontalSlider_servoMinV.setPageStep(1)
        self.horizontalSlider_servoMinV.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMinV.setObjectName("horizontalSlider_servoMinV")
        self.horizontalSlider_servoMaxV = QtWidgets.QSlider(self.widget_6)
        self.horizontalSlider_servoMaxV.setGeometry(QtCore.QRect(30, 120, 160, 22))
        self.horizontalSlider_servoMaxV.setMinimum(45)
        self.horizontalSlider_servoMaxV.setMaximum(140)
        self.horizontalSlider_servoMaxV.setPageStep(1)
        self.horizontalSlider_servoMaxV.setProperty("value", 120)
        self.horizontalSlider_servoMaxV.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMaxV.setObjectName("horizontalSlider_servoMaxV")
        self.label_servoMinV = QtWidgets.QLabel(self.widget_6)
        self.label_servoMinV.setGeometry(QtCore.QRect(20, 30, 50, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMinV.setFont(font)
        self.label_servoMinV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMinV.setObjectName("label_servoMinV")
        self.label_servoMaxV = QtWidgets.QLabel(self.widget_6)
        self.label_servoMaxV.setGeometry(QtCore.QRect(150, 90, 50, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMaxV.setFont(font)
        self.label_servoMaxV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMaxV.setObjectName("label_servoMaxV")
        self.widget_7 = QtWidgets.QWidget(self.tab_2)
        self.widget_7.setGeometry(QtCore.QRect(100, 350, 220, 90))
        self.widget_7.setStyleSheet("#widget_7 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalSlider_servoTemp = QtWidgets.QSlider(self.widget_7)
        self.horizontalSlider_servoTemp.setGeometry(QtCore.QRect(50, 50, 160, 22))
        self.horizontalSlider_servoTemp.setMinimum(50)
        self.horizontalSlider_servoTemp.setMaximum(100)
        self.horizontalSlider_servoTemp.setPageStep(1)
        self.horizontalSlider_servoTemp.setProperty("value", 85)
        self.horizontalSlider_servoTemp.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoTemp.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider_servoTemp.setObjectName("horizontalSlider_servoTemp")
        self.label_20 = QtWidgets.QLabel(self.widget_7)
        self.label_20.setGeometry(QtCore.QRect(58, 10, 111, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.label_servoTemp = QtWidgets.QLabel(self.widget_7)
        self.label_servoTemp.setGeometry(QtCore.QRect(4, 45, 45, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoTemp.setFont(font)
        self.label_servoTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoTemp.setObjectName("label_servoTemp")
        self.widget_8 = QtWidgets.QWidget(self.tab_2)
        self.widget_8.setGeometry(QtCore.QRect(810, 90, 291, 180))
        self.widget_8.setStyleSheet("#widget_8 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_8.setObjectName("widget_8")
        self.label_21 = QtWidgets.QLabel(self.widget_8)
        self.label_21.setGeometry(QtCore.QRect(15, 30, 171, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.widget_8)
        self.label_22.setGeometry(QtCore.QRect(15, 130, 171, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.widget_8)
        self.label_23.setGeometry(QtCore.QRect(15, 80, 171, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_servoCurrentP = QtWidgets.QLabel(self.widget_8)
        self.label_servoCurrentP.setGeometry(QtCore.QRect(210, 25, 50, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoCurrentP.setFont(font)
        self.label_servoCurrentP.setText("")
        self.label_servoCurrentP.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoCurrentP.setObjectName("label_servoCurrentP")
        self.label_servoCurrentV = QtWidgets.QLabel(self.widget_8)
        self.label_servoCurrentV.setGeometry(QtCore.QRect(200, 75, 61, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoCurrentV.setFont(font)
        self.label_servoCurrentV.setText("")
        self.label_servoCurrentV.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoCurrentV.setObjectName("label_servoCurrentV")
        self.label_servoCurrentTemp = QtWidgets.QLabel(self.widget_8)
        self.label_servoCurrentTemp.setGeometry(QtCore.QRect(210, 125, 50, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoCurrentTemp.setFont(font)
        self.label_servoCurrentTemp.setText("")
        self.label_servoCurrentTemp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoCurrentTemp.setObjectName("label_servoCurrentTemp")
        self.widget_9 = QtWidgets.QWidget(self.tab_2)
        self.widget_9.setGeometry(QtCore.QRect(100, 90, 220, 80))
        self.widget_9.setStyleSheet("#widget_9 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_9.setObjectName("widget_9")
        self.label_11 = QtWidgets.QLabel(self.widget_9)
        self.label_11.setGeometry(QtCore.QRect(72, 5, 101, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lineEdit_servoID = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit_servoID.setGeometry(QtCore.QRect(75, 40, 91, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_servoID.setFont(font)
        self.lineEdit_servoID.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_servoID.setObjectName("lineEdit_servoID")
        self.label_32 = QtWidgets.QLabel(self.widget_9)
        self.label_32.setGeometry(QtCore.QRect(20, 40, 48, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.widget_10 = QtWidgets.QWidget(self.tab_2)
        self.widget_10.setGeometry(QtCore.QRect(100, 220, 220, 80))
        self.widget_10.setStyleSheet("#widget_10 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_10.setObjectName("widget_10")
        self.label_14 = QtWidgets.QLabel(self.widget_10)
        self.label_14.setGeometry(QtCore.QRect(55, 5, 131, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.lineEdit_servoDev = QtWidgets.QLineEdit(self.widget_10)
        self.lineEdit_servoDev.setGeometry(QtCore.QRect(75, 40, 91, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.lineEdit_servoDev.setFont(font)
        self.lineEdit_servoDev.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_servoDev.setObjectName("lineEdit_servoDev")
        self.label_24 = QtWidgets.QLabel(self.widget_10)
        self.label_24.setGeometry(QtCore.QRect(5, 40, 65, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.widget_11 = QtWidgets.QWidget(self.tab_2)
        self.widget_11.setGeometry(QtCore.QRect(810, 310, 291, 131))
        self.widget_11.setStyleSheet("#widget_11 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_11.setObjectName("widget_11")
        self.horizontalSlider_servoMove = QtWidgets.QSlider(self.widget_11)
        self.horizontalSlider_servoMove.setGeometry(QtCore.QRect(80, 50, 160, 22))
        self.horizontalSlider_servoMove.setMinimum(0)
        self.horizontalSlider_servoMove.setMaximum(1000)
        self.horizontalSlider_servoMove.setPageStep(1)
        self.horizontalSlider_servoMove.setProperty("value", 500)
        self.horizontalSlider_servoMove.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_servoMove.setObjectName("horizontalSlider_servoMove")
        self.label_34 = QtWidgets.QLabel(self.widget_11)
        self.label_34.setGeometry(QtCore.QRect(100, 10, 101, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_servoMove = QtWidgets.QLabel(self.widget_11)
        self.label_servoMove.setGeometry(QtCore.QRect(30, 45, 40, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_servoMove.setFont(font)
        self.label_servoMove.setAlignment(QtCore.Qt.AlignCenter)
        self.label_servoMove.setObjectName("label_servoMove")
        self.pushButton_resetPos = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_resetPos.setGeometry(QtCore.QRect(70, 80, 171, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_resetPos.setFont(font)
        self.pushButton_resetPos.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_resetPos.setObjectName("pushButton_resetPos")
        self.label_36 = QtWidgets.QLabel(self.tab_2)
        self.label_36.setGeometry(QtCore.QRect(80, 30, 1041, 22))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.pushButton_quit2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_quit2.setGeometry(QtCore.QRect(820, 490, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_quit2.setFont(font)
        self.pushButton_quit2.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_quit2.setObjectName("pushButton_quit2")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(840, 10, 161, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.widget_12 = QtWidgets.QWidget(self.tab)
        self.widget_12.setGeometry(QtCore.QRect(310, 380, 385, 161))
        self.widget_12.setStyleSheet("#widget_12 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_12.setObjectName("widget_12")
        self.label_25 = QtWidgets.QLabel(self.widget_12)
        self.label_25.setGeometry(QtCore.QRect(5, 30, 15, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.widget_12)
        self.label_26.setGeometry(QtCore.QRect(5, 80, 15, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.widget_12)
        self.label_27.setGeometry(QtCore.QRect(5, 133, 15, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.horizontalSlider_LMin = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_LMin.setGeometry(QtCore.QRect(20, 35, 169, 22))
        self.horizontalSlider_LMin.setMaximum(255)
        self.horizontalSlider_LMin.setPageStep(1)
        self.horizontalSlider_LMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LMin.setObjectName("horizontalSlider_LMin")
        self.horizontalSlider_AMin = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_AMin.setGeometry(QtCore.QRect(20, 85, 169, 22))
        self.horizontalSlider_AMin.setMaximum(255)
        self.horizontalSlider_AMin.setPageStep(1)
        self.horizontalSlider_AMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AMin.setObjectName("horizontalSlider_AMin")
        self.horizontalSlider_BMin = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_BMin.setGeometry(QtCore.QRect(20, 135, 169, 22))
        self.horizontalSlider_BMin.setMaximum(255)
        self.horizontalSlider_BMin.setPageStep(1)
        self.horizontalSlider_BMin.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BMin.setObjectName("horizontalSlider_BMin")
        self.label_LMin = QtWidgets.QLabel(self.widget_12)
        self.label_LMin.setGeometry(QtCore.QRect(80, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_LMin.setFont(font)
        self.label_LMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LMin.setObjectName("label_LMin")
        self.label_AMin = QtWidgets.QLabel(self.widget_12)
        self.label_AMin.setGeometry(QtCore.QRect(80, 60, 51, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_AMin.setFont(font)
        self.label_AMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AMin.setObjectName("label_AMin")
        self.label_BMin = QtWidgets.QLabel(self.widget_12)
        self.label_BMin.setGeometry(QtCore.QRect(80, 110, 51, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_BMin.setFont(font)
        self.label_BMin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BMin.setObjectName("label_BMin")
        self.horizontalSlider_LMax = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_LMax.setGeometry(QtCore.QRect(210, 35, 169, 22))
        self.horizontalSlider_LMax.setMaximum(255)
        self.horizontalSlider_LMax.setPageStep(1)
        self.horizontalSlider_LMax.setProperty("value", 255)
        self.horizontalSlider_LMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_LMax.setObjectName("horizontalSlider_LMax")
        self.horizontalSlider_AMax = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_AMax.setGeometry(QtCore.QRect(210, 85, 169, 22))
        self.horizontalSlider_AMax.setMaximum(255)
        self.horizontalSlider_AMax.setPageStep(1)
        self.horizontalSlider_AMax.setProperty("value", 255)
        self.horizontalSlider_AMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_AMax.setObjectName("horizontalSlider_AMax")
        self.horizontalSlider_BMax = QtWidgets.QSlider(self.widget_12)
        self.horizontalSlider_BMax.setGeometry(QtCore.QRect(210, 135, 169, 22))
        self.horizontalSlider_BMax.setMaximum(255)
        self.horizontalSlider_BMax.setPageStep(1)
        self.horizontalSlider_BMax.setProperty("value", 255)
        self.horizontalSlider_BMax.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_BMax.setObjectName("horizontalSlider_BMax")
        self.label_LMax = QtWidgets.QLabel(self.widget_12)
        self.label_LMax.setGeometry(QtCore.QRect(270, 10, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_LMax.setFont(font)
        self.label_LMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_LMax.setObjectName("label_LMax")
        self.label_AMax = QtWidgets.QLabel(self.widget_12)
        self.label_AMax.setGeometry(QtCore.QRect(270, 60, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_AMax.setFont(font)
        self.label_AMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_AMax.setObjectName("label_AMax")
        self.label_BMax = QtWidgets.QLabel(self.widget_12)
        self.label_BMax.setGeometry(QtCore.QRect(270, 110, 51, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_BMax.setFont(font)
        self.label_BMax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_BMax.setObjectName("label_BMax")
        self.widget_15 = QtWidgets.QWidget(self.tab)
        self.widget_15.setGeometry(QtCore.QRect(740, 380, 85, 161))
        self.widget_15.setStyleSheet("#widget_15 {border:1px solid #242424;\n"
"border-color: rgb(200, 200, 200);}")
        self.widget_15.setObjectName("widget_15")
        self.comboBox_color = QtWidgets.QComboBox(self.widget_15)
        self.comboBox_color.setGeometry(QtCore.QRect(10, 30, 69, 22))
        self.comboBox_color.setObjectName("comboBox_color")
        self.pushButton_labWrite = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_labWrite.setGeometry(QtCore.QRect(5, 110, 75, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_labWrite.setFont(font)
        self.pushButton_labWrite.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_labWrite.setObjectName("pushButton_labWrite")
        self.pushButton_addcolor = QtWidgets.QPushButton(self.widget_15)
        self.pushButton_addcolor.setGeometry(QtCore.QRect(5, 60, 75, 41))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_addcolor.setFont(font)
        self.pushButton_addcolor.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_addcolor.setObjectName("pushButton_addcolor")
        self.pushButton_connect = QtWidgets.QPushButton(self.tab)
        self.pushButton_connect.setGeometry(QtCore.QRect(100, 410, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_connect.setFont(font)
        self.pushButton_connect.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.label_process = QtWidgets.QLabel(self.tab)
        self.label_process.setGeometry(QtCore.QRect(120, 50, 400, 300))
        self.label_process.setText("")
        self.label_process.setObjectName("label_process")
        self.label_orign = QtWidgets.QLabel(self.tab)
        self.label_orign.setGeometry(QtCore.QRect(680, 50, 400, 300))
        self.label_orign.setText("")
        self.label_orign.setObjectName("label_orign")
        self.pushButton_disconnect = QtWidgets.QPushButton(self.tab)
        self.pushButton_disconnect.setGeometry(QtCore.QRect(100, 490, 121, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.pushButton_disconnect.setFont(font)
        self.pushButton_disconnect.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.pushButton_quit2_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_quit2_2.setGeometry(QtCore.QRect(990, 480, 100, 50))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(16)
        self.pushButton_quit2_2.setFont(font)
        self.pushButton_quit2_2.setStyleSheet("QPushButton{background-color: rgb(255, 165, 0);}\n"
"QPushButton:hover{background-color:  rgb(255, 210, 0);}\n"
"QPushButton{border-radius:5px;}")
        self.pushButton_quit2_2.setObjectName("pushButton_quit2_2")
        self.widget_15.raise_()
        self.widget_12.raise_()
        self.label_8.raise_()
        self.pushButton_connect.raise_()
        self.label_process.raise_()
        self.label_orign.raise_()
        self.pushButton_disconnect.raise_()
        self.pushButton_quit2_2.raise_()
        self.tabWidget.addTab(self.tab, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "ArmPi1.1"))
        self.label_ID6.setText(_translate("Form", "ID:6"))
        self.lineEdit_6.setText(_translate("Form", "500"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\">左</p></body></html>"))
        self.label_d6.setText(_translate("Form", "0"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\">右</p></body></html>"))
        self.label_action.setText(_translate("Form", "动作组："))
        self.Button_DelectSingle.setText(_translate("Form", "单个擦除"))
        self.Button_AllDelect.setText(_translate("Form", "全部擦除"))
        self.Button_RunAction.setText(_translate("Form", "动作组运行"))
        self.Button_StopAction.setText(_translate("Form", "停止"))
        self.Button_Quit.setText(_translate("Form", "退出"))
        self.Button_Reflash.setText(_translate("Form", "刷新"))
        self.checkBox.setText(_translate("Form", "循环"))
        self.Button_Run.setText(_translate("Form", "运行"))
        self.Button_ReadDeviation.setText(_translate("Form", "读取偏差"))
        self.Button_DownloadDeviation.setText(_translate("Form", "下载偏差"))
        self.Button_ReSetServos.setText(_translate("Form", "复位舵机"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "编号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "时间"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "ID:1"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "ID:2"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "ID:3"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "ID:4"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "ID:5"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("Form", "ID:6"))
        self.Button_OpenActionGroup.setText(_translate("Form", "打开动作文件"))
        self.Button_SaveActionGroup.setText(_translate("Form", "保存动作文件"))
        self.Button_TandemActionGroup.setText(_translate("Form", "串联动作文件"))
        self.label_time.setText(_translate("Form", "动作时间"))
        self.lineEdit_time.setText(_translate("Form", "1000"))
        self.Button_AddAction.setText(_translate("Form", "添加动作"))
        self.Button_DelectAction.setText(_translate("Form", "删除动作"))
        self.Button_UpdateAction.setText(_translate("Form", "更新动作"))
        self.Button_InsertAction.setText(_translate("Form", "插入动作"))
        self.Button_ServoPowerDown.setText(_translate("Form", "马达掉电"))
        self.Button_AngularReadback.setText(_translate("Form", "角度回读"))
        self.Button_MoveUpAction.setText(_translate("Form", "上移动作"))
        self.Button_MoveDownAction.setText(_translate("Form", "下移动作"))
        self.label_time_2.setText(_translate("Form", "总时长"))
        self.label.setText(_translate("Form", "ms"))
        self.label_5.setText(_translate("Form", "s"))
        self.label_TotalTime.setText(_translate("Form", "0"))
        self.Button_DelectAllAction.setText(_translate("Form", "删除全部"))
        self.label_ID5.setText(_translate("Form", "ID:5"))
        self.lineEdit_5.setText(_translate("Form", "500"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_d5.setText(_translate("Form", "0"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_ID1.setText(_translate("Form", "ID:1"))
        self.lineEdit_1.setText(_translate("Form", "500"))
        self.label_d1.setText(_translate("Form", "0"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"center\">开</p><p align=\"justify\"><br/></p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"center\">合</p></body></html>"))
        self.label_ID4.setText(_translate("Form", "ID:4"))
        self.lineEdit_4.setText(_translate("Form", "500"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.label_d4.setText(_translate("Form", "0"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_ID2.setText(_translate("Form", "ID:2"))
        self.lineEdit_2.setText(_translate("Form", "500"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"center\">左</p></body></html>"))
        self.label_d2.setText(_translate("Form", "0"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"center\">右</p></body></html>"))
        self.label_ID3.setText(_translate("Form", "ID:3"))
        self.lineEdit_3.setText(_translate("Form", "500"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"center\">上</p></body></html>"))
        self.label_d3.setText(_translate("Form", "0"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"center\">下</p></body></html>"))
        self.radioButton_zn.setText(_translate("Form", "中文"))
        self.radioButton_en.setText(_translate("Form", "English"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "普通模式"))
        self.pushButton_read.setText(_translate("Form", "读取"))
        self.pushButton_set.setText(_translate("Form", "设置"))
        self.pushButton_default.setText(_translate("Form", "默认"))
        self.label_17.setText(_translate("Form", "角度范围"))
        self.label_servoMin.setText(_translate("Form", "0"))
        self.label_servoMax.setText(_translate("Form", "1000"))
        self.label_19.setText(_translate("Form", "电压范围"))
        self.label_servoMinV.setText(_translate("Form", "4.5V"))
        self.label_servoMaxV.setText(_translate("Form", "12V"))
        self.label_20.setText(_translate("Form", "温度范围"))
        self.label_servoTemp.setText(_translate("Form", "85℃"))
        self.label_21.setText(_translate("Form", "当前角度："))
        self.label_22.setText(_translate("Form", "当前温度："))
        self.label_23.setText(_translate("Form", "当前电压："))
        self.label_11.setText(_translate("Form", "舵机ID"))
        self.lineEdit_servoID.setText(_translate("Form", "1"))
        self.label_32.setText(_translate("Form", "ID"))
        self.label_14.setText(_translate("Form", "舵机偏差"))
        self.label_24.setText(_translate("Form", "-125~125"))
        self.label_34.setText(_translate("Form", "舵机调试"))
        self.label_servoMove.setText(_translate("Form", "500"))
        self.pushButton_resetPos.setText(_translate("Form", "中位"))
        self.label_36.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">注意：使用下面的功能时，请确保控制器只连接了一个舵机，否则会引起冲突!</span></p></body></html>"))
        self.pushButton_quit2.setText(_translate("Form", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "舵机调试工具"))
        self.label_8.setText(_translate("Form", "400x300原图"))
        self.label_25.setText(_translate("Form", "L"))
        self.label_26.setText(_translate("Form", "A"))
        self.label_27.setText(_translate("Form", "B"))
        self.label_LMin.setText(_translate("Form", "0"))
        self.label_AMin.setText(_translate("Form", "0"))
        self.label_BMin.setText(_translate("Form", "0"))
        self.label_LMax.setText(_translate("Form", "255"))
        self.label_AMax.setText(_translate("Form", "255"))
        self.label_BMax.setText(_translate("Form", "255"))
        self.pushButton_labWrite.setText(_translate("Form", "保存"))
        self.pushButton_addcolor.setText(_translate("Form", "新增"))
        self.pushButton_connect.setText(_translate("Form", "连接"))
        self.pushButton_disconnect.setText(_translate("Form", "断开"))
        self.pushButton_quit2_2.setText(_translate("Form", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "摄像头工具"))

    def englishUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"justify\">left</p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"justify\">right</p></body></html>"))
        self.label_action.setText(_translate("Form", "Action group："))
        self.Button_DelectSingle.setText(_translate("Form", "Erase"))
        self.Button_AllDelect.setText(_translate("Form", "Erase all"))
        self.Button_RunAction.setText(_translate("Form", "Run action group"))
        self.Button_StopAction.setText(_translate("Form", "Stop"))
        self.Button_Quit.setText(_translate("Form", "Exit"))
        self.Button_Reflash.setText(_translate("Form", "Refresh"))
        self.checkBox.setText(_translate("Form", "Loop"))
        self.Button_Run.setText(_translate("Form", "Run"))
        self.Button_ReadDeviation.setText(_translate("Form", "Read deviation"))
        self.Button_DownloadDeviation.setText(_translate("Form", "Download deviation"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Index"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Time"))
        self.Button_OpenActionGroup.setText(_translate("Form", "Open action file"))
        self.Button_SaveActionGroup.setText(_translate("Form", "Save action file"))
        self.Button_TandemActionGroup.setText(_translate("Form", "Integrate files"))
        self.label_time.setText(_translate("Form", "Running time"))
        self.Button_AddAction.setText(_translate("Form", "Add action"))
        self.Button_DelectAction.setText(_translate("Form", "Delete action"))
        self.Button_UpdateAction.setText(_translate("Form", "Update action"))
        self.Button_InsertAction.setText(_translate("Form", "Insert action"))
        self.Button_ServoPowerDown.setText(_translate("Form", "Manual coding"))
        self.Button_AngularReadback.setText(_translate("Form", "Read angle"))
        self.Button_MoveUpAction.setText(_translate("Form", "Move up"))
        self.Button_MoveDownAction.setText(_translate("Form", "Move down"))
        self.label_time_2.setText(_translate("Form", "Total time"))
        self.Button_DelectAllAction.setText(_translate("Form", "Delete all"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"justify\">up</p></body></html>"))
        self.label_15.setText(_translate("Form", "<html><head/><body><p align=\"justify\">down</p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p align=\"justify\">release</p></body></html>"))
        self.label_3.setText(_translate("Form", "<html><head/><body><p align=\"justify\">close</p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p align=\"justify\">down</p></body></html>"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"justify\">up</p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p align=\"justify\">left</p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p align=\"justify\">right</p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p align=\"justify\">up</p></body></html>"))
        self.label_9.setText(_translate("Form", "<html><head/><body><p align=\"justify\">down/p></body></html>"))
        self.Button_ReSetServos.setText(_translate("Form", "Reset servo"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("Form", "Normal Mode"))
        self.pushButton_read.setText(_translate("Form", "Read"))
        self.pushButton_set.setText(_translate("Form", "Setting"))
        self.pushButton_default.setText(_translate("Form", "Default"))
        self.label_17.setText(_translate("Form", "Angle"))
        self.label_19.setText(_translate("Form", "Voltage"))
        self.label_20.setText(_translate("Form", "Temperature"))
        self.label_21.setText(_translate("Form", "Current angle："))
        self.label_22.setText(_translate("Form", "Current temperature："))
        self.label_23.setText(_translate("Form", "Current voltage："))
        self.label_11.setText(_translate("Form", "Servo ID"))
        self.label_14.setText(_translate("Form", "Servo deviation"))
        self.label_34.setText(_translate("Form", "Servo debug"))
        self.pushButton_resetPos.setText(_translate("Form", "Middle position"))
        self.label_36.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ff0000;\">Note:before debugging servo,make sure that the servo controller is connected with ONE servo.Otherwise it may cause a conflict!</span></p></body></html>"))
        self.pushButton_quit2.setText(_translate("Form", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Servo Test"))
        self.label_8.setText(_translate("Form", "400x300image"))
        self.pushButton_labWrite.setText(_translate("Form", "Save"))
        self.pushButton_addcolor.setText(_translate("Form", "Add"))
        self.pushButton_connect.setText(_translate("Form", "Connect"))
        self.pushButton_disconnect.setText(_translate("Form", "Disconnect"))
        self.pushButton_quit2_2.setText(_translate("Form", "Exit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Camera Tool"))

import resource_rc
